<?php
exec('php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php ' .
    '& php -f test.php');